version: '3.8'

services:
  project-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-prod-container
    ports:
      - "8080:8080"
    volumes:
      - ./db.json:/app/db.json
    restart: unless-stopped
